### ISSUE TITLE
./fips setup android fails with "main" java.lang.NoClassDefFoundError after inflate

### ISSUE THREAD

**Issue by neshume** [floooh/fips#172]
using the latest fips to setup android fails after inflate

**Comment by floooh** [comment]
Hmm, strange. What OS are you on, and what does ```java -version``` say?

I'm on OSX 10.13.4 beta, and java 1.8.0_25, and it works here. 

I also tested on Windows 7 (but can't check right now).

**Comment by neshume** [comment]
hi f,

thx for the fast response.

java version 

java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)

also attached is the full output from ./fips setup android..
[fips-android-issue.txt](https://github.com/floooh/fips/files/1723687/fips-android-issue.txt)

**Comment by neshume** [comment]
ooh and os is macosx 10.13.2 

;o)

**Comment by neshume** [comment]
hi f,

thx for the fast response.

java version

java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)

also attached is the full output from ./fips setup android..
[fips-android-issue.txt](https://github.com/floooh/fips/files/1725195/fips-android-issue.txt)

**Comment by neshume** [comment]
Hi floooh,

Indeed it does not work with 1.9+ jdk.. when I uninstalled and installed specific 1.8.0161 version ... all setup worked ;o)

cheers,

neshume

**Comment by cheyao** [comment]
Also have this issue, my jdk version is
```
openjdk version "21.0.1" 2023-10-17 LTS
OpenJDK Runtime Environment Temurin-21.0.1+12 (build 21.0.1+12-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.1+12 (build 21.0.1+12-LTS, mixed mode)
```

**Comment by cheyao** [comment]
Thanks! Installing jdk8 solved the problem. 
Just a note for anyone else having this problem, you gotta also use
```
export JAVA_HOME=`/usr/libexec/java_home -v 8.0`
```
To change the jdk version
